FROM registry.ci.openshift.org/ocp/4.11:installer AS builder

ARG DIRECT_DOWNLOAD=false

USER root:root

RUN dnf install -y jq wget https://kojihub.stream.centos.org/kojifiles/packages/coreos-installer/0.11.0/3.el8/$(arch)/coreos-installer-0.11.0-3.el8.$(arch).rpm
COPY fetch_image.sh /usr/local/bin/
RUN /usr/local/bin/fetch_image.sh


FROM registry.ci.openshift.org/ocp/4.11:base

COPY --from=builder /usr/bin/coreos-installer /usr/bin/
COPY --from=builder /output/coreos/* /coreos/

COPY scripts/* /bin/

# Include this container in the release image payload
LABEL io.openshift.release.operator=true
