FROM registry.ci.openshift.org/origin/4.12:machine-config-operator as mcd
FROM registry.ci.openshift.org/origin/4.12:hyperkube-rpms as hyperkube-rpms
FROM registry.ci.openshift.org/origin/4.12:cli as cli

FROM quay.io/coreos-assembler/fcos:testing-devel
WORKDIR /tmp
COPY manifests/ /manifests/
COPY bootstrap/ /bootstrap/
COPY --from=hyperkube-rpms /srv/repo/ /srv/repo/
COPY --from=mcd /usr/bin/machine-config-daemon /usr/libexec/machine-config-daemon
COPY --from=cli /usr/bin/oc /usr/bin/oc
COPY overlay.d/ /tmp/overlay
COPY openshift-os/overlay.d/ /tmp/overlay
RUN curl -o /srv/repo/crio.rpm -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/Fedora_36/x86_64/cri-o-1.24.1-2.1.fc36.x86_64.rpm \
    && curl -o /srv/repo/cri-tools.rpm -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Fedora_36/x86_64/cri-tools-1.24.0-.fc36.1.1.x86_64.rpm \
    && cp -irvf /tmp/overlay/*/* / \
    && mkdir /extensions \
    && rpm-ostree install \
      NetworkManager-ovs \
      open-vm-tools \
      qemu-guest-agent \
      glusterfs \
      glusterfs-fuse \
    && rpm -Uvh /srv/repo/*.rpm \
    && rm -rf /var/cache /srv/repo \
    && ostree container commit
LABEL io.openshift.release.operator=true \
      io.openshift.build.version-display-names="machine-os=Fedora CoreOS" \
      io.openshift.build.versions="machine-os=412.36.0"
ENTRYPOINT ["/noentry"]
