apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: okd-fcos

resources:
  - ../../buildconfigs
  - ../../pipelines
  - 40-okd-rpms.yaml
patches:
  - patch: |-
      apiVersion: build.openshift.io/v1
      kind: BuildConfig
      metadata:
        name: not-used
        labels:
          change-build-arg-tags: ""
      spec:
        strategy:
          dockerStrategy:
            buildArgs:
              - name: "TAGS"
                value: "fcos"
    target:
      labelSelector: "change-build-arg-tags==true"
      kind: BuildConfig
  - patch: |-
      - op: add
        path: /spec/tags/-
        value:
          from:
            kind: DockerImage
            name: registry.fedoraproject.org/fedora:37
          name: fedora37
      - op: add
        path: "/spec/tags/-"
        value:
          name: fedora-coreos
          from:
            kind: DockerImage
            name: quay.io/fedora/fedora-coreos:next-devel
          referencePolicy:
            type: Source
    target:
      kind: ImageStream
      name: tools
  - patch: |-
      - op: replace
        path: "/spec/source/git/ref"
        value: release-4.12
    target:
      kind: BuildConfig
      name: fedora-coreos
  - patch: |-
      - op: add
        path: "/spec/tags/-"
        value:
          name: machine-os-content
          from:
            kind: ImageStreamTag
            name: release:fedora-coreos
    target:
      kind: ImageStream
      name: release
  - patch: |-
      - op: add
        path: "/spec/tasks/3/params/0/value"
        value:
          - tests
          - network-tools
          - ovn-kubernetes-microshift
          - fedora-coreos
          - okd-rpms
    target:
      kind: Pipeline
      name: build-from-scratch
  - patch: |-
      - op: replace
        path: "/spec/tasks/20/params/0/value"
        value:
          - artifacts
          - tests
          - network-tools
          - machine-os-content
          - odk-rpms
    target:
      kind: Pipeline
      name: full-rebuild
