apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-from-scratch
spec:
  params:
    - name: result-mirror-location
      type: string
      description: Location to mirror resulting images
      default: quay.io/<your-organization>/okd-release
    - name: result-image
      type: string
      description: Resulting release location
      default: quay.io/<your-organization>/okd-release:4.12.0-0.okd-centos9-build-from-scratch
    - name: result-image-name
      type: string
      description: Internal release name
      default: 4.12.0-0.okd-centos9-build-from-scratch
    - name: max_concurrent_builds
      type: string
      default: "8"
  workspaces:
    - name: push-credentials
  tasks:
    - name: prepare-build-images
      taskRef:
        name: batch-build
      params:
        - name: max_concurrent_builds
          value: "1"
        - name: build_configs
          value:
            - builder
            - forked-dockerfiles
            - base
            - cli
    - name: batch-01
      timeout: "4h0m0s"
      runAfter:
      - prepare-build-images
      taskRef:
        name: batch-build
      params:
        - name: max_concurrent_builds
          value: "$(params.max_concurrent_builds)"
        - name: build_configs
          value:
          - agent-installer-node-agent
          - agent-installer-orchestrator
          - alibaba-cloud-controller-manager
          - alibaba-cloud-csi-driver
          - alibaba-disk-csi-driver-operator
          - alibaba-machine-controllers
          - apiserver-network-proxy
          - aws-cloud-controller-manager
          - aws-cluster-api-controllers
          - aws-ebs-csi-driver-operator
          - aws-ebs-csi-driver
          - aws-machine-controllers
          - aws-pod-identity-webhook
          - azure-cloud-controller-manager
          - azure-cloud-node-manager
          - azure-cluster-api-controllers
          - azure-disk-csi-driver-operator
          - azure-disk-csi-driver
          - azure-file-csi-driver-operator
          - azure-file-csi-driver
          - azure-machine-controllers
          - baremetal-machine-controllers
          - baremetal-operator
          - baremetal-runtimecfg
          - branding
          - cloud-credential-operator
          - cloud-network-config-controller
          - cluster-authentication-operator
          - cluster-autoscaler-operator
          - cluster-autoscaler
          - cluster-baremetal-operator
          - cluster-bootstrap
          - cluster-capi-controllers
          - cluster-capi-operator
          - cluster-cloud-controller-manager-operator
          - cluster-config-operator
          - cluster-control-plane-machine-set-operator
          - cluster-csi-snapshot-controller-operator
          - cluster-dns-operator
          - cluster-etcd-operator
          - cluster-image-registry-operator
          - cluster-ingress-operator
          - cluster-kube-apiserver-operator
          - cluster-kube-cluster-api-operator
          - cluster-kube-controller-manager-operator
          - cluster-kube-scheduler-operator
          - cluster-kube-storage-version-migrator-operator
          - cluster-machine-approver
          - cluster-monitoring-operator
          - cluster-network-operator
          - cluster-openshift-apiserver-operator
          - cluster-openshift-controller-manager-operator
          - cluster-policy-controller
          - cluster-samples-operator
          - cluster-storage-operator
          - cluster-update-keys
          - cluster-version-operator
          - configmap-reloader
          - console-operator
          - container-networking-plugins
          - contour-operator
          - contour
          - coredns
          - csi-driver-manila-operator
          - csi-driver-manila
          - csi-driver-nfs
          - csi-driver-shared-resource-operator
          - csi-driver-shared-resource-webhook
          - csi-driver-shared-resource
          - csi-external-attacher
          - csi-external-provisioner
          - csi-external-resizer
          - csi-external-snapshotter
          - csi-livenessprobe
          - csi-node-driver-registrar
          - csi-snapshot-controller
          - csi-snapshot-validation-webhook
          - docker-builder
          - docker-registry
          - egress-router-cni
          - etcd
          - external-dns
          - gcp-cloud-controller-manager
          - gcp-cluster-api-controllers
          - gcp-machine-controllers
          - gcp-pd-csi-driver-operator
          - gcp-pd-csi-driver
          - haproxy-router-base
          - hypershift
          - ibm-cloud-controller-manager
          - ibm-vpc-block-csi-driver-operator
          - ibm-vpc-block-csi-driver
          - ibm-vpc-node-label-updater
          - ibmcloud-machine-controllers
          - insights-operator
          - ironic-agent
          - ironic-machine-os-downloader
          - ironic-static-ip-manager
          - k8s-prometheus-adapter
          - keepalived-ipfailover
          - kube-proxy
          - kube-rbac-proxy
          - kube-state-metrics
          - kube-storage-version-migrator
          - local-storage-static-provisioner
          - machine-api-operator
          - machine-config-operator
          - machine-image-customization-controller
          - multus-admission-controller
          - multus-cni
          - multus-networkpolicy
          - multus-route-override-cni
          - multus-whereabouts-ipam-cni
          - must-gather
          - bond-cni
          - network-metrics-daemon
          - nutanix-machine-controllers
          - oauth-apiserver
          - oauth-proxy
          - oauth-server
          - oc-mirror
          - cli-artifacts
          - openshift-apiserver
          - openshift-controller-manager
          - openshift-state-metrics
          - openstack-cinder-csi-driver-operator
          - openstack-cinder-csi-driver
          - openstack-cloud-controller-manager
          - openstack-machine-api-provider
          - openstack-machine-controllers
          - operator-lifecycle-manager
          - operator-marketplace
          - ovirt-csi-driver-operator
          - ovirt-csi-driver
          - ovirt-installer
          - ovirt-machine-controllers
          - pod
          - powervs-cloud-controller-manager
          - powervs-machine-controllers
          - prom-label-proxy
          - prometheus-alertmanager
          - prometheus-config-reloader
          - prometheus-node-exporter
          - prometheus-operator-admission-webhook
          - prometheus-operator
          - prometheus
          - route-controller-manager
          - service-ca-operator
          - telemeter
          - thanos
          - vsphere-cloud-controller-manager
          - vsphere-cluster-api-controllers
          - vsphere-csi-driver-operator
          - vsphere-csi-driver-syncer
          - vsphere-csi-driver
          - vsphere-problem-detector
          - cluster-node-tuning-operator
          - ironic
          - ironic-hardware-inventory-recorder
          - libvirt-machine-controllers
          - operator-registry
          - sdn
          - console
          - baremetal-installer
          - installer-artifacts
          - installer
          - hyperkube
    - name: batch-02
      timeout: "2h0m0s"
      runAfter:
      - batch-01
      taskRef:
        name: batch-build
      params:
        - name: build_configs
          value:
          - agent-installer-api-server
          - agent-installer-csr-approver
          - artifacts
          - tools
          - haproxy-router
          - ovn-kubernetes
          - ovn-kubernetes-base
          - machine-os-images
          - deployer
    - name: batch-03
      timeout: "1h0m0s"
      runAfter:
      - batch-02
      taskRef:
        name: batch-build
      params:
        - name: build_configs
          value:
          - tests
          - network-tools
          - ovn-kubernetes-microshift
    - name: new-release
      timeout: "2h0m0s"
      runAfter:
      - batch-03
      taskRef:
        name: new-release
        kind: Task
      workspaces:
        - workspace: push-credentials
          name: credentials
      params:
        - name: release-mirror-location
          value: $(params.result-mirror-location)
        - name: release-image
          value: $(params.result-image)
        - name: release-image-name
          value: $(params.result-image-name)
