apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: tools
spec:
  lookupPolicy:
    local: true
  tags:
    - name: centos9
      from:
        kind: DockerImage
        name: 'quay.io/centos/centos:stream9'
      referencePolicy:
        type: Local
      importPolicy:
        importMode: PreserveOriginal # Needs OKD 4.13
    - name: fedora36
      from:
        kind: DockerImage
        name: 'quay.io/fedora/fedora:36'
      referencePolicy:
        type: Local
      importPolicy:
        importMode: PreserveOriginal # Needs OKD 4.13
