apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: alibaba-cloud-controller-manager
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/cloud-provider-alibaba-cloud'
      ref: release-4.12
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: openshift-hack/images/Dockerfile.openshift
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:alibaba-cloud-controller-manager'
