apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: csi-driver-manila
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/cloud-provider-openstack'
      ref: release-4.15
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/manila-csi-plugin/Dockerfile
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:csi-driver-manila'
