apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: csi-driver-shared-resource-webhook
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/csi-driver-shared-resource'
      ref: release-4.12
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.webhook
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:csi-driver-shared-resource-webhook'
