apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: haproxy-router-base
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/router'
      ref: release-4.12
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/router/base/Dockerfile.rhel
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:haproxy-router-base'
