apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ironic-machine-os-downloader
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/ironic-rhcos-downloader'
      ref: release-4.12
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.ocp
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:ironic-machine-os-downloader'
