apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ironic-hardware-inventory-recorder
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/ironic-hardware-inventory-recorder-image'
      ref: release-4.15
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:builder'
        as:
          - 'registry.ci.openshift.org/ocp/builder:rhel-8-base-openshift-4.11'
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
        - sourcePath: /code/ironic-hardware-inventory-recorder/Dockerfile.centos9
          destinationDir: "."
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.centos9
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:ironic-hardware-inventory-recorder'
