apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: keepalived-ipfailover
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/images'
      ref: release-4.12
    contextDir: ipfailover/keepalived
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:keepalived-ipfailover'
