apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: kube-state-metrics
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/kube-state-metrics'
      ref: release-4.15
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.ocp
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:kube-state-metrics'
