apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: network-metrics-daemon
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/network-metrics-daemon'
      ref: release-4.12
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.openshift
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:network-metrics-daemon'
