apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mutanix-cloud-controller-manager
  labels:
    resources-profile: high
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/cloud-provider-nutanix-cloud'
      ref: release-4.12
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: openshift/Dockerfile.openshift
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:nutanix-cloud-controller-manager'
