apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: oauth-server
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/oauth-server'
      ref: release-4.12
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/Dockerfile.rhel
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:oauth-server'
