apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: oc-mirror
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/oc-mirror'
      ref: release-4.12
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/cli/Dockerfile.ci
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:oc-mirror'
