apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: prom-label-proxy
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/prom-label-proxy'
      ref: release-4.12
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.ocp
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:prom-label-proxy'
