apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: vsphere-cluster-api-controllers
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/cluster-api-provider-vsphere'
      ref: release-4.12
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: openshift/Dockerfile.openshift
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:vsphere-cluster-api-controllers'
