apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: artifacts
spec:
  source:
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:cli-artifacts'
        as:
          - 'release:cli-artifacts'
      - from:
          kind: ImageStreamTag
          name: 'release:hyperkube'
        as:
          - 'release:hyperkube'
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
          - sourcePath: /code/artifacts/Dockerfile.centos9
            destinationDir: "."
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.centos9
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:artifacts'
