apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: tools
  namespace: okd
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/oc'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
        - sourcePath: /code/tools/Dockerfile.centos9
          destinationDir: "./images/tools"
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: images/tools/Dockerfile.centos9
      from:
        kind: "ImageStreamTag"
        name: "release:cli"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:tools'
