apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: kuryr-controller
  failureDescription: kuryr-cni-rpm-base fails to build
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/kuryr-kubernetes'
      ref: release-4.15
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: openshift-kuryr-controller-rhel8.Dockerfile
      from:
        kind: "ImageStreamTag"
        name: "release:kuryr-cni-rpm-base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:kuryr-controller'
