FROM registry.ci.openshift.org/ocp/builder:rhel-8-base-openshift-4.11

RUN dnf update -y && \
    dnf install -y centos-release-openstack-yoga && \
    dnf install -y openstack-ironic-python-agent lshw smartmontools iproute python3-hardware && \
    dnf clean all && \
    rm -rf /var/cache/{yum,dnf}/*

COPY ./runironic-agent.sh /bin/runironic-agent

ENTRYPOINT ["/bin/runironic-agent"]

LABEL io.openshift.release.operator true
